In [1]:
import numpy as np

A = np.random.rand(3, 4)
B = np.random.rand(4, 5)

C = np.dot(A, B)

print("Matrix A:", A)
print("Matrix B:", B)
print("Matrix C (A * B):", C)


Matrix A: [[0.77703174 0.10142516 0.79450269 0.83781863]
 [0.04789858 0.05946031 0.22909659 0.50170468]
 [0.85408858 0.29208838 0.9914545  0.12558415]]
Matrix B: [[0.86931509 0.39697649 0.39782854 0.12351527 0.92329161]
 [0.00196935 0.46296455 0.87401834 0.19078165 0.29038043]
 [0.61443213 0.41442141 0.97902978 0.74369532 0.16855859]
 [0.91356067 0.60823864 0.7948245  0.4409468  0.01697682]]
Matrix C (A * B): [[1.92925129 1.19427218 1.84153342 1.07562673 0.89502252]
 [0.64085802 0.44664133 0.69408438 0.40886328 0.10862401]
 [1.46695755 0.96154476 1.66555226 0.95393409 1.04263976]]


In [11]:
a = np.ones(5)
b = np.ones((3, 4))
a1 = np.empty(5)
a2 = np.arange(10)
a3 = np.linspace(0, 1, 5)
a4 = np.eye(2)

In [14]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = np.array([0, 2])
cols = np.array([0, 2])
print(rows,cols)
print(b[rows, cols])

a = np.array([1, 2, 3, 4, 5])
print(a[a > 3])

[0 2] [0 2]
[1 9]
[4 5]


In [15]:
a = np.array([1, 2, 3])
b = np.append(a, [4, 5])
print(b)  

c = np.array([[1, 2], [3, 4]])
d = np.append(c, [[5, 6]], axis=0)
print(d)

[1 2 3 4 5]
[[1 2]
 [3 4]
 [5 6]]


In [16]:
a = np.array([1, 2, 3, 4, 5])
b = np.insert(a, 2, [10, 20])
print(b) 

c = np.array([[1, 2], [3, 4]])
d = np.insert(c, 1, [10, 20], axis=1)
print(d)

[ 1  2 10 20  3  4  5]
[[ 1 10  2]
 [ 3 20  4]]


In [17]:
a = np.array([1, 2, 3, 4, 5])
b = np.delete(a, [0, 2])
print(b) 

c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.delete(c, 1, axis=1)
print(d)

[2 4 5]
[[1 3]
 [4 6]]


In [2]:
import numpy as np
A = np.random.rand(3, 4)
A_T = np.transpose(A)
print("Matrix A:\n", A)
print("Transpose of A:\n", A_T)


Matrix A:
 [[0.79408167 0.05790818 0.80864383 0.29775125]
 [0.88520165 0.50717017 0.61467713 0.0848662 ]
 [0.57548203 0.08782642 0.71249099 0.76166201]]
Transpose of A:
 [[0.79408167 0.88520165 0.57548203]
 [0.05790818 0.50717017 0.08782642]
 [0.80864383 0.61467713 0.71249099]
 [0.29775125 0.0848662  0.76166201]]


In [3]:
import numpy as np
data = np.random.rand(100)
mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)
print("Data:\n", data)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)


Data:
 [0.99345893 0.48182158 0.54605459 0.73266119 0.11479776 0.31745752
 0.29731732 0.14310866 0.79055205 0.47588436 0.23351358 0.87053251
 0.20224505 0.38346669 0.58934411 0.5774407  0.20677973 0.40734454
 0.77497255 0.67847822 0.20804699 0.74852494 0.284002   0.00942546
 0.03337736 0.79693908 0.6897511  0.50132948 0.76921499 0.60340551
 0.61373052 0.6251709  0.24470917 0.85558428 0.56268421 0.86782437
 0.73490752 0.64931328 0.37338554 0.87835206 0.00353982 0.35684821
 0.51338273 0.26759893 0.26842123 0.93083299 0.57674377 0.82150192
 0.77781932 0.54731125 0.49422652 0.8517693  0.26385478 0.03591569
 0.76163917 0.08455157 0.94127729 0.87351898 0.23590045 0.58310199
 0.05000015 0.94593025 0.95721139 0.07096463 0.52762805 0.3379982
 0.6502965  0.69684844 0.66650954 0.72116926 0.21709532 0.79553672
 0.30412303 0.19834281 0.57970465 0.21536146 0.61211365 0.63012739
 0.26652048 0.43724903 0.855142   0.47495956 0.20150591 0.41716431
 0.12747589 0.96688843 0.13521461 0.57264912 0.16873659 

In [4]:
import numpy as np
array = np.arange(16)
reshaped_array = np.reshape(array, (4, 4))

print("Original array:\n", array)
print("Reshaped array (4x4):\n", reshaped_array)


Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Reshaped array (4x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [5]:
import numpy as np
array1 = np.random.rand(3, 4)
array2 = np.random.rand(3, 4)
concatenated = np.concatenate((array1, array2), axis=0)

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Concatenated array:\n", concatenated)


Array 1:
 [[0.13035154 0.67149598 0.4773816  0.93070229]
 [0.26755455 0.7799914  0.6337309  0.55250673]
 [0.56566262 0.8011524  0.68598293 0.15191544]]
Array 2:
 [[0.50967335 0.79790335 0.15934482 0.44669611]
 [0.50341237 0.05026797 0.93144689 0.68221763]
 [0.59390482 0.95547577 0.40867396 0.44215371]]
Concatenated array:
 [[0.13035154 0.67149598 0.4773816  0.93070229]
 [0.26755455 0.7799914  0.6337309  0.55250673]
 [0.56566262 0.8011524  0.68598293 0.15191544]
 [0.50967335 0.79790335 0.15934482 0.44669611]
 [0.50341237 0.05026797 0.93144689 0.68221763]
 [0.59390482 0.95547577 0.40867396 0.44215371]]


In [7]:
#random sampling

import numpy as np
sample = np.random.normal(loc=0, scale=1, size=10)
print("Random sample:\n", sample)


Random sample:
 [ 0.01964216  1.15915914 -0.54609957  0.80134675 -0.75540264  1.2493379
 -0.30597703  0.52858562  0.03971196 -0.63422025]


In [8]:
#masking
import numpy as np
data = np.random.rand(10)
mask = data > 0.5
filtered_data = data[mask]

print("Original data:\n", data)
print("Mask:\n", mask)
print("Filtered data:\n", filtered_data)


Original data:
 [0.05270487 0.93653691 0.41856246 0.17964936 0.58123197 0.93823442
 0.14087162 0.94844543 0.03723187 0.55664512]
Mask:
 [False  True False False  True  True False  True False  True]
Filtered data:
 [0.93653691 0.58123197 0.93823442 0.94844543 0.55664512]


In [9]:
import numpy as np
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)

print("Solution of the system:\n", x)


Solution of the system:
 [2. 3.]


In [10]:
import numpy as np
A = np.random.rand(3, 3)
det_A = np.linalg.det(A)

print("Matrix A:\n", A)
print("Determinant of A:", det_A)


Matrix A:
 [[0.97076108 0.53508594 0.52165012]
 [0.13218693 0.00949296 0.48068433]
 [0.53221368 0.50782574 0.09642394]]
Determinant of A: -0.07362707707841125
